export const sample_foods: any[] = [
  {
    // id: "1",
    name: "burger-1",
    cookTime: "10-20",
    price: 10,
    fav: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "assets/foods/b1.png",
    tags: ["Burger", "Lunch"],
  },
  {
    // id: "2",
    name: "burger-2",
    price: 20,
    cookTime: "20-30",
    fav: true,
    origins: ["persia", "middle east", "china"],
    stars: 4.7,
    imageUrl: "assets/foods/b5.png",
    tags: ["Burger", "Lunch"],
  },
  {
    // id: "3",
    name: "burger-3",
    price: 5,
    cookTime: "10-15",
    fav: false,
    origins: ["germany", "us"],
    stars: 3.5,
    imageUrl: "assets/foods//b6.png",
    tags: ["Burger", "Lunch"],
  },
  {
    // id: "4",
    name: "burger-4",
    price: 2,
    cookTime: "15-20",
    fav: true,
    origins: ["belgium", "france"],
    stars: 3.3,
    imageUrl: "assets/foods/b7.png",
    tags: ["Burger", "Lunch"],
  },
  {
    // id: "5",
    name: "burger-5",
    price: 11,
    cookTime: "40-50",
    fav: false,
    origins: ["india", "asia"],
    stars: 3.0,
    imageUrl: "assets/foods/b8.png",
    tags: ["Burger", "Lunch"],
  },
  {
    // id: "6",
    name: "burger-6",
    price: 9,
    cookTime: "40-50",
    fav: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "assets/foods//b9.png",
    tags: ["Burger", "Lunch"],
  },
  {
    // id: "7",
    name: "burger-7",
    price: 9,
    cookTime: "40-50",
    fav: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "assets/foods/b10.png",
    tags: ["Burger", "Lunch"],
  },
  {
    // id: "8",
    name: "burger-8",
    price: 9,
    cookTime: "40-50",
    fav: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "assets/foods/b11.png",
    tags: ["Burger", "Lunch"],
  },
  {
    // id: "9",
    name: "burger-9",
    price: 9,
    cookTime: "40-50",
    fav: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "assets/foods/b12.png",
    tags: ["Burger", "Lunch"],
  },
  {
    // id: "10",
    name: "pizza-1",
    price: 9,
    cookTime: "40-50",
    fav: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "assets/foods/p1.png",
    tags: ["Pizza", "Lunch"],
  },
  {
    // id: "11",
    name: "pizza-2",
    price: 9,
    cookTime: "40-50",
    fav: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "assets/foods/p2.png",
    tags: ["Pizza", "Lunch"],
  },
  {
    // id: "12",
    name: "pizza-3",
    price: 9,
    cookTime: "40-50",
    fav: false,
    origins: ["America"],
    stars: 4.0,
    imageUrl: "assets/foods/p3.png",
    tags: ["Pizza", "Lunch"],
  },
  {
    // id: "13",
    name: "pizza-4",
    price: 9,
    cookTime: "40-50",
    fav: false,
    origins: ["spain"],
    stars: 4.0,
    imageUrl: "assets/foods/p4.png",
    tags: ["Pizza", "Lunch"],
  },
  {
    // id: "14",
    name: "pizza-5",
    price: 9,
    cookTime: "40-50",
    fav: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "assets/foods/p5.png",
    tags: ["Pizza", "Lunch"],
  },
  {
    // id: "15",
    name: "pizza-6",
    price: 9,
    cookTime: "40-50",
    fav: false,
    origins: ["german"],
    stars: 4.0,
    imageUrl: "assets/foods/p6.png",
    tags: ["Pizza", "Lunch"],
  },
  {
    // id: "16",
    name: "fry-1",
    price: 9,
    cookTime: "40-50",
    fav: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "assets/foods/f1.png",
    tags: ["Fry", "SlowFood"],
  },
  {
    // id: "17",
    name: "fry-2",
    price: 9,
    cookTime: "40-50",
    fav: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "assets/foods/f2.png",
    tags: ["Fry", "SlowFood"],
  },
  {
    // id: "18",
    name: "fry-3",
    price: 9,
    cookTime: "40-50",
    fav: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "assets/foods/f3.png",
    tags: ["Fry", "SlowFood"],
  },
  {
    // id: "19",
    name: "fry-4",
    price: 9,
    cookTime: "40-50",
    fav: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "assets/foods/f4.png",
    tags: ["Fry", "SlowFood"],
  },
  {
    // id: "20",
    name: "fry-5",
    price: 9,
    cookTime: "40-50",
    fav: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "assets/foods/f5.png",
    tags: ["Fry", "SlowFood"],
  },
];

export const sample_tags: any[] = [
  { name: "All", count: 6 },
  { name: "Burger", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Fry", count: 3 },
  { name: "SlowFood", count: 2 },
  { name: "Lunch", count: 1 },
  { name: "Soup", count: 1 },
];

export const sample_users: any[] = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "Jane Doe",
    email: "Jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: false,
  },
];
