import { Food } from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id: '1',
    name: 'burger-1',
    cookTime: '10-20',
    price: 10,
    fav: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/burger/b1.png',
    tags: ['Burger'],
  },
  {
    id: '2',
    name: 'burger-2',
    price: 20,
    cookTime: '20-30',
    fav: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/burger/b2.png',
    tags: ['Burger', 'Lunch'],
  },
  {
    id: '3',
    name: 'burger-3',
    price: 5,
    cookTime: '10-15',
    fav: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/burger/b3.png',
    tags: ['Burger'],
  },
  {
    id: '4',
    name: 'burger-4',
    price: 2,
    cookTime: '15-20',
    fav: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/burger/b4.png',
    tags: ['Burger'],
  },
  {
    id: '5',
    name: 'burger-5',
    price: 11,
    cookTime: '40-50',
    fav: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/burger/b5.png',
    tags: ['Burger'],
  },
  {
    id: '6',
    name: 'burger-6',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/burger/b6.png',
    tags: ['Burger'],
  },
  {
    id: '7',
    name: 'burger-7',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/burger/b7.png',
    tags: ['Burger'],
  },
  {
    id: '8',
    name: 'burger-8',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/burger/b8.png',
    tags: ['Burger'],
  },
  {
    id: '9',
    name: 'burger-9',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/burger/b9.png',
    tags: ['Burger'],
  },
  {
    id: '10',
    name: 'pizza-1',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/pizza/p1.png',
    tags: ['Pizza'],
  },
  {
    id: '11',
    name: 'pizza-2',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/pizza/p2.png',
    tags: ['Pizza'],
  },
  {
    id: '12',
    name: 'pizza-3',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['America'],
    stars: 4.0,
    imageUrl: 'assets/pizza/p3.png',
    tags: ['Pizza'],
  },
  {
    id: '13',
    name: 'pizza-4',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['spain'],
    stars: 4.0,
    imageUrl: 'assets/pizza/p4.png',
    tags: ['Pizza'],
  },
  {
    id: '14',
    name: 'pizza-5',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/pizza/p5.png',
    tags: ['Pizza'],
  },
  {
    id: '15',
    name: 'pizza-6',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['german'],
    stars: 4.0,
    imageUrl: 'assets/pizza/p6.png',
    tags: ['Pizza'],
  },
  {
    id: '16',
    name: 'Fried Tandoori Chicken',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['india'],
    stars: 4.0,
    imageUrl: 'assets/fried/f1.png',
    tags: ['Fried-chicken'],
  },
  {
    id: '17',
    name: 'The Ultimate Southern Fried Chicken',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['USA'],
    stars: 4.0,
    imageUrl: 'assets/fried/f2.png',
    tags: ['Fried-chicken'],
  },
  {
    id: '18',
    name: 'fry-3',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/fried/f3.png',
    tags: ['Fry', 'SlowFood'],
  },
  {
    id: '19',
    name: 'fry-4',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/fried/f4.png',
    tags: ['Fry', 'SlowFood'],
  },
  {
    id: '20',
    name: 'fry-5',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/fried/f5.png',
    tags: ['Fry', 'SlowFood'],
  },
  {
    id: '20',
    name: 'fry-6',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/fried/f6.png',
    tags: ['Fry', 'SlowFood'],
  },
  {
    id: '20',
    name: 'fry-7',
    price: 9,
    cookTime: '40-50',
    fav: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/fried/f7.png',
    tags: ['Fry', 'SlowFood'],
  },
];

export const sample_tags: Tag[] = [
  { name: 'All', count: 6 },
  { name: 'Burger', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Fried-chicken', count: 3 },
  { name: 'Drinks', count: 1 },
];
